baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Narrative Introduction to Probabilistic Computing'
theme = 'hugo-theme-relearn'
images = ['images/chibanyplain.png']
[params]
    math = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
